<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Api\BaseController as BaseController;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use App\Models\EmployeeBreak;
use App\Models\Attendance;
use App\Models\Employee;
use App\Models\EmployeeShift;  // Add this for EmployeeShift model


use App\Models\AppSetting;
use Illuminate\Support\Facades\Broadcast;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class EmployeeBreakController extends BaseController
{
    public function markBreak(Request $request)
    {
        $employeeId = $request->user()->employee->id;
        \Log::info('markBreak called', ['employeeId' => $employeeId, 'request' => $request->all()]);

        $request->validate([
            'break_type' => 'required|in:general,official',
            'reason' => 'required_if:break_type,official|nullable|string|max:255',
            'attendance_id' => 'required|exists:attendances,id',
        ]);

        // Fetch employee shift
        $employeeShift = EmployeeShift::where('emp_id', $employeeId)
            ->with('shift')
            ->latest('created_at')
            ->first();

        if (!$employeeShift || !$employeeShift->shift) {
            return response()->json(['success' => false, 'message' => 'Employee shift not found.'], 404);
        }

        // Validate that attendance is NOT checked out
        $attendance = Attendance::find($request->attendance_id);
        if ($attendance && $attendance->check_out) {
            \Log::warning('Blocked markBreak request for checked-out attendance', [
                'employeeId' => $employeeId,
                'attendance_id' => $attendance->id,
                'check_out' => $attendance->check_out
            ]);
            return response()->json([
                'success' => false,
                'message' => 'Cannot start break. You are already checked out.'
            ], 400);
        }


        // Get correct shift date
        $shiftDate = resolve_shift_date($employeeShift);
        \Log::info('Resolved shift date for markBreak', ['shiftDate' => $shiftDate]);

        $breakType = ucfirst(strtolower($request->break_type));

        // If user starts an official break while auto-inactivity break is active, convert it
        // instead of closing the auto break and creating a duplicate record.
        if ($breakType === 'Official') {
            $activeAuto = EmployeeBreak::where('emp_id', $employeeId)
                ->whereIn('status', ['On Break', 'On break', 'Ongoing'])
                ->where('type', 'General')
                ->where(function ($q) {
                    $q->where('reason', 'like', 'Auto break:%')
                        ->orWhere('reason', 'like', 'Auto-break%');
                })
                ->first();

            if ($activeAuto) {
                $activeAuto->type = 'Official';
                $activeAuto->reason = $request->reason;
                $activeAuto->save();

                $breakData = standardize_break_data_for_pusher($employeeId, $shiftDate, $activeAuto->id, $request->attendance_id);
                event(new \App\Events\BreakUpdated($employeeId, $breakData));
                clear_employee_app_data_cache($employeeId);

                return response()->json([
                    'success' => true,
                    'message' => 'Break started.',
                    'break' => $activeAuto,
                ]);
            }
        }

        // Close lingering active breaks — discard auto-generated ones instead of logging duplicates.
        EmployeeBreak::where('emp_id', $employeeId)
            ->whereIn('status', ['On Break', 'On break', 'Ongoing'])
            ->get()
            ->each(function ($break) {
                if ($break->isAutoGenerated()) {
                    $break->delete();
                } else {
                    $break->endBreak(['end_time' => now_with_timezone()]);
                }
            });

        // Create break
        $employeeBreak = new EmployeeBreak();
        $employeeBreak->emp_id = $employeeId;
        $employeeBreak->shift_date = $shiftDate; // ★ FIX
        $employeeBreak->attendance_id = $request->attendance_id;
        $employeeBreak->type = $breakType;
        $employeeBreak->reason = $request->reason;
        
        // Handle idle_duration if provided (in seconds)
        // This effectively "backdates" the break start to when the user actually went idle
        $startTime = now_with_timezone();
        if ($request->has('idle_duration')) {
            $idleSeconds = (int)$request->idle_duration;
            // Cap at 2 hours to prevent crazy values
            if ($idleSeconds > 0 && $idleSeconds < 7200) {
                 $startTime = $startTime->subSeconds($idleSeconds);
            }
        }
        
        $employeeBreak->start_time = $startTime;
        $employeeBreak->status = 'On Break';
        $employeeBreak->save();

        // Send update
        $breakData = standardize_break_data_for_pusher($employeeId, $shiftDate, $employeeBreak->id, $request->attendance_id);
        event(new \App\Events\BreakUpdated($employeeId, $breakData));

        clear_employee_app_data_cache($employeeId);

        return response()->json([
            'success' => true,
            'message' => 'Break started.',
            'break' => $employeeBreak
        ]);
    }
    public function endBreak(Request $request, $id = null)
    {
        $employeeId = $request->user()->employee->id;
        \Log::info('endBreak called', ['employeeId' => $employeeId, 'request' => $request->all(), 'id' => $id]);

        $request->validate([
            'break_type' => 'required|in:general,official',
            'reason' => 'required_if:break_type,official|nullable|string|max:255',
            'attendance_id' => 'required|exists:attendances,id',
        ]);

        // Fetch employee shift
        $employeeShift = EmployeeShift::where('emp_id', $employeeId)
            ->with('shift')
            ->latest('created_at')
            ->first();

        if (!$employeeShift || !$employeeShift->shift) {
            return response()->json(['success' => false, 'message' => 'Employee shift not found.'], 404);
        }

        // Correct shift date
        $shiftDate = resolve_shift_date($employeeShift);
        \Log::info('Resolved shift date for endBreak', ['shiftDate' => $shiftDate]);

        // Find active break
        if (!$id) {
            $break = EmployeeBreak::where('emp_id', $employeeId)
                ->whereIn('status', ['On Break', 'On break', 'Ongoing'])
                ->where('shift_date', $shiftDate)
                ->latest()
                ->first();

            if (!$break) {
                return response()->json(['success' => false, 'message' => 'No active break found.'], 404);
            }
        } else {
            $break = EmployeeBreak::where('emp_id', $employeeId)->findOrFail($id);
        }

        // === END BREAK USING ROBUST MODEL LOGIC ===
        $break->endBreak([
            'type' => ucfirst(strtolower($request->break_type)),
            'reason' => $request->reason,
            'attendance_id' => $request->attendance_id,
            'end_time' => now_with_timezone(),
        ]);

        EmployeeBreak::purgeSupersededAutoBreaks($employeeId, $shiftDate, $break->id);

        // Trigger Pusher update
        $breakData = standardize_break_data_for_pusher($employeeId, $shiftDate, null, $request->attendance_id);
        event(new \App\Events\BreakUpdated($employeeId, $breakData));

        clear_employee_app_data_cache($employeeId);

        return response()->json([
            'success' => true,
            'message' => 'Break ended.'
        ]);
    }
    public function currentAttendance(Request $request)
    {
        $employeeId = $request->user()->employee->id;
        $attendance = Attendance::where('emp_id', $employeeId)
            ->whereDate('date', now()->toDateString())  // Current day
            ->first();
        return response()->json(['attendance_id' => $attendance?->id]);
    }
    public function breakStatus($employeeId)
    {
        try {
            if ($employeeId != Auth::user()->employee->id) {
                return $this->sendError('Unauthorized access.', [], 403);
            }

            $assignedShift = $this->getTodayAssignedShift($employeeId);
            if (!$assignedShift) {
                return $this->sendResponse(['onBreak' => false], 'No assigned shift found.');
            }

            $shiftDate = Carbon::parse($assignedShift->shift_date)->toDateString();
            $attendance = Attendance::where('emp_id', $employeeId)
                ->whereDate('shift_date', $shiftDate)
                ->latest()
                ->first();

            if (!$attendance) {
                return $this->sendResponse(['onBreak' => false], 'No attendance found for assigned shift date.');
            }

            $ongoingBreak = EmployeeBreak::where('emp_id', $employeeId)
                ->where('status', 'On Break')
                ->first();

            return $this->sendResponse(
                ['onBreak' => $ongoingBreak ? true : false],
                'Break status fetched successfully.'
            );
        } catch (\Exception $e) {
            return $this->sendError('Failed to fetch break status.', ['error' => $e->getMessage()], 500);
        }
    }

    public function getBreaks(Request $request)
    {
        try {
            $employeeId = Auth::user()->employee->id;
            $breaks = EmployeeBreak::where('emp_id', $employeeId)->paginate(10); // Added pagination
            return $this->sendResponse($breaks, 'Breaks retrieved successfully.');
        } catch (\Exception $e) {
            return $this->sendError('Failed to retrieve breaks.', ['error' => $e->getMessage()], 500);
        }
    }

    public function getBreakStats()
    {
        try {
            $user = Auth::user();
            $employee = $user->employee;

            if (!$employee) {
                return response()->json(['error' => 'Employee not found.'], 404);
            }

            $assignedShift = $this->getTodayAssignedShift($employee->id);
            if (!$assignedShift) {
                return response()->json(['error' => 'Assigned shift not found.'], 404);
            }

            $shiftDate = Carbon::parse($assignedShift->shift_date)->toDateString();
            $allowedBreakMinutes = get_effective_break_minutes((int) $employee->id, $shiftDate);

            $breaks = EmployeeBreak::where('emp_id', $employee->id)
                ->whereIn('type', ['General', 'Official']) // Include both types
                ->where('status', 'Completed')
                ->whereDate('end_time', $shiftDate)
                ->get();

            $totalSpentMinutes = 0;
            foreach ($breaks as $break) {
                if ($break->start_time && $break->end_time) {
                    try {
                        $start = Carbon::parse($break->start_time);
                        $end = Carbon::parse($break->end_time);
                        if ($end->greaterThan($start)) {
                            $totalSpentMinutes += $start->diffInMinutes($end);
                        }
                    } catch (\Exception $e) {
                        continue;
                    }
                }
            }

            $totalSpentMinutes = round($totalSpentMinutes);
            $remaining = max(round($allowedBreakMinutes - $totalSpentMinutes), 0);
            $exceeded = max(round($totalSpentMinutes - $allowedBreakMinutes), 0);

            $formatMinutes = function ($minutes) {
                $hours = floor($minutes / 60);
                $mins = $minutes % 60;
                $parts = [];
                if ($hours > 0)
                    $parts[] = "$hours hour" . ($hours > 1 ? 's' : '');
                if ($mins > 0)
                    $parts[] = "$mins minute" . ($mins > 1 ? 's' : '');
                return count($parts) > 0 ? implode(' ', $parts) : '0 minutes';
            };

            $employeeService = app(\App\Services\EmployeeService::class);
            $breakStats = calculate_break_stats($employee, $assignedShift, $shiftDate);

            return response()->json($breakStats);
        } catch (\Exception $e) {
            \Log::error('getBreakStats: Failed to fetch break stats.', [
                'employeeId' => $employee->id ?? null,
                'error' => $e->getMessage(),
            ]);
            return response()->json(['error' => 'Failed to fetch break stats.'], 500);
        }
    }

    public function getAppSettings()
    {
        $settings = AppSetting::all()->pluck('value', 'key');
        return response()->json($settings);
    }

    public function getActiveBreak()
    {
        try {
            $employeeId = Auth::user()->employee->id;
            $assignedShift = getTodayAssignedShift($employeeId);
            $shiftDate = web_resolve_shift_date($assignedShift);
            $activeBreak = EmployeeBreak::where('emp_id', $employeeId)
                ->where('status', 'On Break')
                ->whereDate('created_at', $shiftDate)
                ->first();

            if ($activeBreak) {
                $duration = $activeBreak->calculateBreakTime();
                return response()->json([
                    'success' => true,
                    'activeBreak' => [
                        'id' => $activeBreak->id,
                        'duration' => $duration,
                    ],
                ]);
            }

            return response()->json(['success' => true, 'activeBreak' => null]);
        } catch (\Exception $e) {
            \Log::error('getActiveBreak: Failed to fetch active break.', ['emp_id' => $employeeId, 'error' => $e->getMessage()]);
            return response()->json(['success' => false, 'message' => 'Failed to fetch active break'], 500);
        }
    }

    public function getBreakDuration($id)
    {
        try {
            $employeeId = Auth::user()->employee->id;
            $break = EmployeeBreak::where('emp_id', $employeeId)->findOrFail($id);
            $duration = $break->status === 'On Break'
                ? (int) round($break->created_at->diffInMinutes(now_with_timezone()))
                : (int) $break->spent_minutes;
            return response()->json(['success' => true, 'duration' => $duration]);
        } catch (\Exception $e) {
            \Log::error('getBreakDuration: Failed to fetch break duration.', ['emp_id' => $employeeId, 'break_id' => $id, 'error' => $e->getMessage()]);
            return response()->json(['success' => false, 'message' => 'Failed to fetch break duration: ' . $e->getMessage()], 500);
        }
    }

    public function getBreakLive(Request $request)
    {
        try {
            $employeeId = Auth::user()->employee->id;
            $breakId = $request->query('break_id');
            $break = EmployeeBreak::where('emp_id', $employeeId)->findOrFail($breakId);

            $employee = Employee::find($employeeId);
            if (!$employee)
                return null;
            // Latest shift
            $employeeShift = EmployeeShift::where('emp_id', $employeeId)
                ->with('shift')
                ->latest('created_at')
                ->first();

            if (!$employeeShift || !$employeeShift->shift)
                return null;

            $shiftDate = resolve_shift_date($employeeShift);

            // Fetch attendance_id if shift is assigned and attendance exists for today
            $attendanceId = null;
            if ($shiftDate) {
                $attendance = Attendance::where('emp_id', $employeeId)
                    ->where('shift_date', $shiftDate)
                    ->latest()
                    ->first();
                $attendanceId = $attendance ? $attendance->id : null;
            }

            if ($break->status !== 'On Break') {
                return response()->json(['success' => false, 'message' => 'Break is not active'], 400);
            }
            
            // Pass attendanceId to ensure we only get breaks for the current session
            $breakStats = calculate_break_stats($employee, $employeeShift, $shiftDate, $attendanceId);

            return response()->json([  
                'success' => true,
                'duration' => $breakStats['active_break_duration'],
                'total_spent' => $breakStats['total_spent_minutes'],
                'remaining' => $breakStats['remaining_minutes'],
                'exceeded' => $breakStats['exceeded_minutes'],
                'working_hours' => $breakStats['working_hours'],
                'working_minutes' => $breakStats['working_minutes'],
                'attendance_id' => $attendanceId,
            ]);
        } catch (\Exception $e) {
            \Log::error('getBreakLive: Failed to fetch live break data.', [
                'emp_id' => $employeeId,
                'break_id' => $breakId,
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString()
            ]);
            return response()->json(['success' => false, 'message' => 'Failed to fetch live break data'], 500);
        }
    }
}